### ISSUE TITLE
Niespójności dokumentacji

### ISSUE THREAD

**Issue by bbprojectnet** [mnastalski/przelewy24-laravel#1]
Cześć,

Implementuje po raz pierwszy płatności z Przelewy24, i też poznaje flow akurat tego dostawcy, nie mniej, w README są pewne błędy/niespójności:

```
$order->payment_id = $register->orderId();
```

Ta klasa nie ma w ogóle metody orderId a samo Przelewy24 nie zwraca tej informacji.

```
        $order = Order::find(
            $webhook->orderId()
        );
```

Nie bardzo rozumiem w jaki sposób orderId z przelewów miało by akurat odpowiadać kluczowi głównemu naszego modelu?

**Comment by mnastalski** [comment]
Cześć,

Faktycznie było to mocno pomieszane.

Przypisanie `payment_id` powinno wykorzystywać `token()`:

```php
$order->payment_id = $register->token();
```

Wyszukiwanie zamówienia powinno się odbywać po tym przypisanym `payment_id`:

```php
$order = Order::firstWhere('payment_id', $webhook->sessionId());
```

`verify()` też miało złe parametry, powinno wykorzystywać `payment_id` z zamówienia (lub `sessionId()` z webhooka) i `orderId()` z webhooka, czyli:

```php
$this->przelewy24->transactions()->verify(
    $order->payment_id,
    $webhook->orderId(),
    $order->amount,
);
```

Zaktualizowałem README
